### ISSUE TITLE
Loading Scripts from Resource packs

### ISSUE THREAD

**Issue by roidrole** [friendlyhj/ZenUtils#68]
It would greatly improve Resource Packs' power to be able to load CT scripts through them. There are a few benefits to being able to do that : 
1- Ability for players to activate/deactivate CT scripts (only supports reloadable methods? Only on game restart? I'll leave that to you to determine whatever is easier to implement)
2- Ability to share CT scripts more easily through Curseforge/Modrinth, by packing them in a resource pack
3- Ability for resource packs to use Mixins to change the appearance of some hard-coded textures (as a dark mode resource pack dev, I am most interested in this feature)
4- Ability for resource packs to change recipes (some resource packs, along with localization and texture changes, would benefit from minor recipe changes for thematic integrity)

The way I imagine it working is CT looking for assets/zenutils/scripts and/or assets/crafttweaker/scripts folder for zs files to load. Even better if we can override scripts placed in .minecraft/scripts, but this is not required

Yes, this is basically a datapack backport through ZS and I love it

**Comment by Krutoy242** [comment]
Double the feature request.

- Some GUIs like LittleTiles one drawing its GUI with code rather than texture. I would like to make E2EE in "Dark Mode", but let player enable/disable it on demand.
![image](https://github.com/user-attachments/assets/55d4507c-574d-42a9-9944-e630e4f4c8ca)

- Its very hard to distribute ZenScript modules.
  For example, my [Portal Spread](https://www.curseforge.com/minecraft/customization/do-portal_spread-zs) downloaded only 32 times, duh. I believe this is because it require dedicated installation by spreading files in `scripts/` and `resources/` folders, so modpack makers add it once and download count doesn't change.
  Throught, **portal_spread.zs** including server-side scripts, the idea may not work. But in future, I could make more dedicated scripts, related to JEI or other clientside-only features, that sounds perfectly matching.

**Comment by friendlyhj** [comment]
Check https://www.curseforge.com/minecraft/mc-mods/resource-mod-loader. It allows you wrap scripts and resources as a mod.
